server:
  port: 10001

wiki-config:
  raw-urls-topic: raw-urls
  unique-urls-topic: unique-urls
  crawlers-group: crawlers
  unifiers-group: unifiers

spring:
  application:
    name: Wiki Crawler
  kafka:
    bootstrap-servers: localhost:9092
logging:
  level:
    root: info
    my.wiki: debug
